sudo: false
cache: bundler
language: ruby
rvm:
  - 2.3.1
  - 2.4.2
before_install: gem install bundler -v 1.14.4
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/848287ce2cec253fc164
    on_success: change
    on_failure: always
    on_start: never
